# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f1dc39d7670>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
a=np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
a = np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
b=a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [10]:
a = np.arange(0,9)
b = a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [11]:
b = np.nonzero([1,2,0,0,4,0])
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [12]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [13]:
a = np.random.random((3,3,3))
print(a)

[[[0.09705277 0.7261926  0.23462063]
  [0.75936956 0.70616576 0.26288384]
  [0.81627646 0.61824762 0.050645  ]]

 [[0.78836404 0.76767498 0.6356888 ]
  [0.62823128 0.66637654 0.78555007]
  [0.91886591 0.21502169 0.05814465]]

 [[0.58494395 0.17896416 0.62664501]
  [0.9490465  0.91300387 0.7474603 ]
  [0.39053939 0.9035041  0.23794735]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [14]:
a = np.random.random((10,10))
print("minimum = ", a.min())
print("maximum = ", a.max())

minimum =  0.004096821606749512
maximum =  0.9760105135070107


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [15]:
a = np.random.random(30)
m = a.mean()
print(m)

0.5397659208967884


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [16]:
a = np.array([[1,0,1], [1,0,1]])
print(a)
print("\n")
b = np.array([[1,1,1], [1,0,1], [1,1,1]])
print(b)
print("\n")
c=np.ones((5,5))
c[1:-1,1:-1]=0
print(c)

[[1 0 1]
 [1 0 1]]


[[1 1 1]
 [1 0 1]
 [1 1 1]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [17]:
x = np.ones(3)
y = np.pad(x, pad_width=1)
y

array([0., 1., 1., 1., 0.])

In [18]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.pad(x, pad_width=1)
y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [20]:
a = np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [21]:
a = np.zeros((8,8))
a[::2,1::2] = 1
a[1::2,::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [22]:
a = np.arange(336).reshape(6,7,8)
np.unravel_index(335,(6,7,8))

(5, 6, 7)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [23]:
np.tile( np.array([[0,1],[1,0]]), (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [24]:
a = np.random.random((5,5))
a_max = a.max()
a_min = a.min()
diff = a_max - a_min
a = (a-a_min)/(a_max-a_min)
a

array([[0.2755828 , 0.50218885, 0.85734749, 0.68444581, 0.7610446 ],
       [1.        , 0.13782853, 0.34475908, 0.31070172, 0.86187667],
       [0.79756536, 0.14810343, 0.96681993, 0.15843427, 0.        ],
       [0.16646747, 0.83325445, 0.76124462, 0.7700914 , 0.47599906],
       [0.05481548, 0.94505596, 0.94198333, 0.46101015, 0.80080197]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [25]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [26]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = np.dot(a,b)
print(a,b,c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] [[0 1]
 [2 3]
 [4 5]] [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [27]:
a = np.arange(20)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-30-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-30-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [32]:
a = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[ 7. -5.  5. -3.  4.  9. -1.  4.  8.  9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [33]:
a = np.random.randint(1,10,10)
b = np.random.randint(1,10,10)
a,b,np.intersect1d(a,b)

(array([1, 7, 6, 4, 7, 3, 5, 9, 2, 5]),
 array([1, 1, 1, 5, 2, 5, 5, 3, 7, 1]),
 array([1, 2, 3, 5, 7]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [34]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [35]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [36]:
today = np.datetime64("today",'D')
tomorrow = today + np.timedelta64(1,"D")
yesterday = today - np.timedelta64(1,"D")
today, yesterday, tomorrow

(numpy.datetime64('2023-01-16'),
 numpy.datetime64('2023-01-15'),
 numpy.datetime64('2023-01-17'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [37]:
d1 = np.arange('2016-07','2016-08', dtype="datetime64[D]")
d1

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [38]:
A = np.arange(1,4, dtype=float)
B = np.arange(1,4, dtype=float) * 2
C = np.arange(1,4, dtype=float) * 3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[ -1.5  -6.  -13.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [39]:
i = 70*np.random.randn(5)
j = np.trunc(i)
k = np.around(i)
l = np.floor(i)
m = np.ceil(i)
n = i.astype(int)
i,j,k,l,m,n

(array([230.14957725, -35.16567296,   2.02631609, -30.06281563,
         62.73569004]),
 array([230., -35.,   2., -30.,  62.]),
 array([230., -35.,   2., -30.,  63.]),
 array([230., -36.,   2., -31.,  62.]),
 array([231., -35.,   3., -30.,  63.]),
 array([230, -35,   2, -30,  62]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [40]:
a = np.ones((5,5)) + np.arange(5)
a

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [41]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=int,count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [42]:
a = np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [43]:
x=np.random.random(10)
x.sort()
x

array([0.02349494, 0.03254412, 0.10983342, 0.32579319, 0.34509725,
       0.36285736, 0.47490303, 0.51152831, 0.8917186 , 0.94471761])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [44]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [45]:
a = np.arange(4)
b = np.arange(4)
np.array_equal(a,b)

True

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [46]:
a=np.zeros(10)
print(a)
a[1]=10
print(a)
a.flags.writeable=False
a[1]=10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [47]:
a = np.random.random((10,2))
print(a,"\n")
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d,"\n")
print(e,"\n")

[[0.53002042 0.47226444]
 [0.09950335 0.47413344]
 [0.61227016 0.93558946]
 [0.00419439 0.62736198]
 [0.82077151 0.96989059]
 [0.54370433 0.73240249]
 [0.19329617 0.31567349]
 [0.84287744 0.63756895]
 [0.01302049 0.50959985]
 [0.63952842 0.22294286]] 

[0.70989813 0.48446201 1.1181245  0.627376   1.27057217 0.91215559
 0.37015289 1.05685218 0.50976617 0.67727403] 

[0.7278375  1.36393477 0.99131889 1.56411068 0.86848241 0.93220452
 1.02136037 0.64759696 1.54525147 0.33543159] 



#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [48]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.96451564, 0.07237006, 0.357232  , 0.17915061, 0.3484314 ,
       0.        , 0.05376855, 0.88353947, 0.88211351, 0.89610934])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [49]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [50]:
a = np.arange(8)
b = a + 0.5
c = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [51]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [52]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [53]:
a = np.arange(5)
b = np.random.uniform(0,5)
index = (np.abs(a-b)).argmin()
index,print(a[index])

1


(1, None)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [54]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-54-1c50e4e32ac3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [55]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.48455724 0.16295801 0.69089595 0.42257593 0.92425468
  0.29651387 0.42627578 0.73418567 0.83665329]
 [0.48455724 0.         0.46897733 0.26138624 0.08134319 0.48923969
  0.19095907 0.32474594 0.28551936 0.37312027]
 [0.16295801 0.46897733 0.         0.71189622 0.39218656 0.94754992
  0.31209496 0.30431437 0.67174598 0.8409379 ]
 [0.69089595 0.26138624 0.71189622 0.         0.34189395 0.23596048
  0.40366884 0.58229136 0.36265606 0.15912179]
 [0.42257593 0.08134319 0.39218656 0.34189395 0.         0.57058093
  0.14525375 0.25160661 0.31827583 0.45312241]
 [0.92425468 0.48923969 0.94754992 0.23596048 0.57058093 0.
  0.63955039 0.79826394 0.4896062  0.1423721 ]
 [0.29651387 0.19095907 0.31209496 0.40366884 0.14525375 0.63955039
  0.         0.30757296 0.46232313 0.54273584]
 [0.42627578 0.32474594 0.30431437 0.58229136 0.25160661 0.79826394
  0.30757296 0.         0.40879087 0.66733733]
 [0.73418567 0.28551936 0.67174598 0.36265606 0.31827583 0.4896062
  0.46232313 0.408790

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [56]:
x = np.arange(1,10,dtype=float)
y = x.astype(int)
print(x)
print(y)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [57]:
from numpy.lib.npyio import genfromtxt
from io import StringIO as st
s = st("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
x = np.genfromtxt(s,delimiter=",",dtype=int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [58]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [59]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [60]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(y)

[[-0.18468332 -0.09367196 -0.25057135 -0.04152327  0.46048427  0.42078819
  -0.34757955  0.40208736 -0.2357315  -0.12959887]
 [-0.12520656  0.04895926  0.39276626 -0.12090793  0.28589445 -0.47428248
   0.04846582 -0.09575433  0.18262477 -0.14255927]
 [-0.2702094   0.15101953  0.28744097 -0.02662333  0.35603142 -0.01740827
   0.24484433 -0.20027614 -0.03603092 -0.48878819]
 [ 0.38790882 -0.07041726 -0.37354497 -0.10973242 -0.26847562 -0.28586124
   0.3342217   0.19673351  0.50808978 -0.3189223 ]
 [-0.1351321   0.39684918 -0.13222649  0.33876211  0.02307602  0.09804844
  -0.13616752 -0.15761677 -0.26774573 -0.02784715]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [61]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[9 5 5]
 [0 2 2]
 [5 4 8]]
[[0 2 2]
 [5 4 8]
 [9 5 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [62]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [63]:
Z = np.random.uniform(0,1,10)
z = 0.5
x = np.abs(Z - z).argmin()
m = Z.flat[x]
print(x, m)

6 0.5419121662339453


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [64]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: 
  z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [65]:
class namedarray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = namedarray(np.arange(10), "range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [67]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)
np.add.at(a, b, 1)
print(a)

[2. 5. 1. 2. 3. 7. 1. 3. 3. 3.]
[ 3.  9.  1.  3.  5. 13.  1.  5.  5.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [68]:
a = [1,2,3,4,5,6]
b = [1,5,7,9,3,5]
c = np.bincount(b,a)
print(c)

[0. 1. 0. 5. 0. 8. 0. 3. 0. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [69]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [70]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[49 44 52 69]
 [46 48 51 57]
 [47 52 66 54]]
[[49 44 52 69]
 [46 48 51 57]
 [47 52 66 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [71]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())

[0.60247989 0.53717383 0.40433266 0.2953356  0.53609936 0.61145852
 0.58643013 0.51511956 0.37573957 0.52115738]
0    0.602480
1    0.537174
2    0.404333
3    0.295336
4    0.536099
5    0.611459
6    0.586430
7    0.515120
8    0.375740
9    0.521157
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [72]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

A,B,np.diag(np.dot(A, B))

(array([[0.04487601, 0.57778477, 0.68673226, 0.74180954, 0.93797944],
        [0.86808492, 0.13535283, 0.09089677, 0.60946357, 0.55117618],
        [0.6524764 , 0.77036237, 0.33763281, 0.11999073, 0.62809828],
        [0.02196545, 0.40417869, 0.56243053, 0.22381087, 0.63443203],
        [0.30056416, 0.03522183, 0.27428171, 0.44757481, 0.55564206]]),
 array([[0.20614484, 0.17501479, 0.99993932, 0.94867869, 0.40817506],
        [0.7201458 , 0.39551261, 0.89661554, 0.98370814, 0.97774141],
        [0.71188465, 0.3903678 , 0.17773952, 0.3033548 , 0.57172709],
        [0.94065152, 0.60640491, 0.13193825, 0.50380444, 0.09206808],
        [0.64253679, 0.31283931, 0.3543912 , 0.22334325, 0.0443357 ]]),
 array([2.21468497, 0.78295591, 1.64159024, 0.84350104, 0.37977705]))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [73]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [74]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [75]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [76]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 30) ( 0, 49) ( 5, 34) ( 5, 52) (19, 24) (19, 55) (19, 59) (19, 98)
 (22, 73) (22, 77) (24, 55) (27, 85) (27, 90) (30, 49) (34, 52) (37, 40)
 (37, 50) (40, 50) (55, 72) (55, 93) (59, 98) (61, 62) (61, 73) (62, 73)
 (66, 87) (66, 99) (72, 93) (73, 77) (85, 90) (87, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [77]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [78]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [79]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [80]:
Z = np.random.uniform(-1.0,1.0,10)
print(Z)
np.negative(Z, out=Z)
print(Z)

[ 0.099164    0.69626503 -0.55387794 -0.63776761  0.65059126 -0.56314996
 -0.31840942 -0.93529868  0.87166684 -0.62592727]
[-0.099164   -0.69626503  0.55387794  0.63776761 -0.65059126  0.56314996
  0.31840942  0.93529868 -0.87166684  0.62592727]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [81]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.98851038  0.41994061  8.09432269  2.39431261  0.58894869  0.53782094
  3.93215404  6.85914381 12.61411576  7.05056945]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [82]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.90304455  0.03508148 11.88340254  8.79024923 12.24460148  2.26051625
   5.69031627 13.83034835 20.80115119  7.14629255]
 [ 7.62751418 10.17866396  1.24815137  4.98339005  1.89063955  4.81615121
   4.44272487  1.73811086  3.95445206  4.50160826]
 [ 5.66767893  8.30655948  1.45572842  2.08706641  1.97202688  3.78869375
   2.59288682  1.73039995  7.9176062   1.11459065]
 [ 0.0338976   2.56897267  6.69006551  2.96867384  0.73769789  2.13188595
   3.15328228  6.03982949 11.06687408  3.6037964 ]
 [ 6.7543383   9.41055288  0.55274164  2.92946484  2.65566909  5.0224884
   3.70115343  1.11692017  7.61868911  0.19641623]
 [12.85696883 15.48039551  5.69438066  9.16629363  0.92221353 10.64153448
   9.76221438  4.91159564  2.19533856  0.55515843]
 [15.33763656 18.1353745   6.53814645  9.53010059  8.2528375  14.81433474
  12.46088826  3.63740933  5.39012747  7.2512356 ]
 [ 9.66970691 12.12330494  4.12108923  8.07241283  6.17831469  5.82503948
   6.36261855  5.47414673  0.35175977  8.29093183]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [83]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 5 8 1 6 4 7 3 5 3]
 [8 5 3 6 4 0 6 1 8 9]
 [1 4 1 9 6 2 3 7 9 3]
 [7 5 0 9 1 9 5 9 7 8]
 [6 9 0 6 9 0 6 5 2 9]
 [2 8 0 7 3 9 5 0 1 5]
 [9 6 1 8 0 8 7 2 5 6]
 [3 9 5 2 7 2 1 1 0 2]
 [7 3 5 9 2 7 4 6 7 8]
 [3 1 2 2 8 5 5 5 9 9]]
[[0 0 0 0 0]
 [0 9 5 8 1]
 [0 8 5 3 6]
 [0 1 4 1 9]
 [0 7 5 0 9]]


<ipython-input-83-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [84]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [85]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [86]:
x = np.random.randint(1,5,5)
print(x) 
print(np.bincount(x)) 
print(np.bincount(x).argmax())

[1 2 3 2 2]
[0 1 3 1]
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [87]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0]-3)
j = 1 + (z.shape[1]-3)
c = stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print(c)

[[[[0 1 4]
   [0 0 3]
   [0 0 0]]

  [[1 4 3]
   [0 3 2]
   [0 0 0]]

  [[4 3 0]
   [3 2 3]
   [0 0 0]]

  [[3 0 1]
   [2 3 3]
   [0 0 2]]

  [[0 1 0]
   [3 3 1]
   [0 2 4]]

  [[1 0 0]
   [3 1 0]
   [2 4 1]]

  [[0 0 3]
   [1 0 3]
   [4 1 3]]

  [[0 3 2]
   [0 3 3]
   [1 3 2]]]


 [[[0 0 3]
   [0 0 0]
   [0 3 3]]

  [[0 3 2]
   [0 0 0]
   [3 3 1]]

  [[3 2 3]
   [0 0 0]
   [3 1 0]]

  [[2 3 3]
   [0 0 2]
   [1 0 0]]

  [[3 3 1]
   [0 2 4]
   [0 0 4]]

  [[3 1 0]
   [2 4 1]
   [0 4 3]]

  [[1 0 3]
   [4 1 3]
   [4 3 1]]

  [[0 3 3]
   [1 3 2]
   [3 1 2]]]


 [[[0 0 0]
   [0 3 3]
   [1 1 3]]

  [[0 0 0]
   [3 3 1]
   [1 3 0]]

  [[0 0 0]
   [3 1 0]
   [3 0 2]]

  [[0 0 2]
   [1 0 0]
   [0 2 0]]

  [[0 2 4]
   [0 0 4]
   [2 0 3]]

  [[2 4 1]
   [0 4 3]
   [0 3 0]]

  [[4 1 3]
   [4 3 1]
   [3 0 1]]

  [[1 3 2]
   [3 1 2]
   [0 1 3]]]


 [[[0 3 3]
   [1 1 3]
   [3 1 4]]

  [[3 3 1]
   [1 3 0]
   [1 4 4]]

  [[3 1 0]
   [3 0 2]
   [4 4 3]]

  [[1 0 0]
   [0 2 0]
   [4 3 4]]

  [[0 0 4]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [88]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  2  6  6  6]
 [ 2  9  8 11 17]
 [ 6  8  2 42 15]
 [ 6 11 42  6  7]
 [ 6 17 15  7  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [90]:
a = np.ones((16,16))
b = 4
c = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0),
                                       np.arange(0, a.shape[1], b), axis=1)
print(c)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [91]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  1 0 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [92]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [93]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [94]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [95]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.81 s ± 65 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
160 ms ± 21.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
166 ms ± 664 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [96]:
a= np.random.randint(0,5,(8,3))
b= np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[2 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [97]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 3]
 [0 3 2]
 [0 4 4]
 [3 2 3]
 [3 2 0]
 [2 0 3]
 [0 2 1]
 [3 3 3]
 [1 2 3]
 [1 4 0]]
[[1 1 3]
 [0 3 2]
 [0 4 4]
 [3 2 3]
 [3 2 0]
 [2 0 3]
 [0 2 1]
 [1 2 3]
 [1 4 0]]
[[1 1 3]
 [0 3 2]
 [0 4 4]
 [3 2 3]
 [3 2 0]
 [2 0 3]
 [0 2 1]
 [1 2 3]
 [1 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [98]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [99]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)    

array([[2.41012185e-01, 6.01682170e-01, 2.96291830e-02, 4.53056003e-01,
        6.47042012e-02, 7.06027800e-03, 1.24189718e-01, 4.30202965e-01,
        2.13139103e-01, 1.32561711e-01],
       [3.97562927e-02, 9.92508012e-02, 4.88749759e-03, 7.47340930e-02,
        1.06733158e-02, 1.16463190e-03, 2.04857807e-02, 7.09643581e-02,
        3.51584737e-02, 2.18667872e-02],
       [6.96767631e-02, 1.73946666e-01, 8.56581406e-03, 1.30978754e-01,
        1.87060222e-02, 2.04113048e-03, 3.59033196e-02, 1.24371928e-01,
        6.16186388e-02, 3.83236677e-02],
       [2.72655628e-01, 6.80679400e-01, 3.35193156e-02, 5.12539516e-01,
        7.31994715e-02, 7.98724980e-03, 1.40495076e-01, 4.86686012e-01,
        2.41122978e-01, 1.49966261e-01],
       [5.58912470e-02, 1.39531396e-01, 6.87107162e-03, 1.05064667e-01,
        1.50050442e-02, 1.63729374e-03, 2.87998641e-02, 9.97649979e-02,
        4.94274190e-02, 3.07413473e-02],
       [7.40503214e-02, 1.84865168e-01, 9.10348380e-03, 1.39200193e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [100]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [101]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [102]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.05405625  0.28074214]
